scrape_configs:
  - job_name: "rag_query"
    static_configs:
      - targets: ["host.docker.internal:8011"]

  - job_name: "rag_ingest"
    static_configs:
      - targets: ["host.docker.internal:8000"]
